name: Kedro Pipeline CI/CD

# Run on a schedule - daily at midnight
on:
  schedule:
    - cron: "15 2 * * *"  # Run daily at 2:15 AM
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-kedro:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install uv
        uv pip install -r requirements.txt --system

    - name: Run Kedro pipeline
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      run: |
        printenv | grep SNOWFLAKE
        kedro run --env=gha
